name: 📝 Documentation
description: Docs, READMEs, or examples improvements
labels: ["documentation"]
title: "[Docs]: "
body:
  - type: input
    id: page
    attributes:
      label: Page / section
      placeholder: "README.md → Installation"
    validations:
      required: true
  - type: textarea
    id: change
    attributes:
      label: What should change?
      placeholder: "Add step to install gh CLI before running scripts"
      render: markdown
    validations:
      required: true
  - type: textarea
    id: refs
    attributes:
      label: References / links
